language: php
services:
  - docker
php:
  - 7.0.22
  - 7.1
before_install:
  - docker build -t 2fa_test_main tests/
install:
  - composer install
script:
  - vendor/bin/peridot spec
  - vendor/bin/php-cs-fixer fix --dry-run -v --diff
  - docker run -d --name=2fa_test_mysql -e MYSQL_DATABASE=2fa_test -e MYSQL_ROOT_PASSWORD=foobar mysql:5.7
  - docker run -ti --rm -v `pwd`:/app --link=2fa_test_mysql -e MYSQL_HOST=2fa_test_mysql -e MYSQL_PASSWORD=foobar 2fa_test_main sh -c 'bundle install && bundle exec rspec spec/*_spec.rb'
