name: 2fa

on: push

jobs:
  kahlan:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        php-versions: ['8.2', '8.3']
    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: gd
      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"
      - uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
      - name: Install dependencies
        run: composer install --no-interaction
      - name: Run Kahlan tests
        run: vendor/bin/kahlan spec
  php-cs-fixer:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        php-versions: ['8.2', '8.3']
    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: gd
      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"
      - uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
      - name: Install dependencies
        run: composer install --no-interaction
      - name: PHP CS fix
        run: vendor/bin/php-cs-fixer fix --dry-run -v --diff
  integration_tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        run: |
          tests/run-with-docker.sh
